extends:
  - "airbnb"
  - "prettier"
  - "prettier/react"
plugins:
  - "react"
env:
  es6: true
  browser: true
globals:
  AFRAME: true
  it: true
parser: "babel-eslint"
rules:
  string: 0
  react/jsx-filename-extension: 0
  react/forbid-prop-types: 0
